name: pyxodr testing

on:
  pull_request:
  push:

jobs:
  test:

    runs-on: ubuntu-latest 
 
    steps: 
      - uses: actions/checkout@v2 
 
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Decrypt example network files
        run: ./tests/decrypt_networks.sh
        env:
          EXAMPLE_XODR_PASSKEY: ${{ secrets.EXAMPLE_XODR_PASSKEY }}
          
      - name: Test with pytest
        run: |
          python -m pytest tests